// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpvkwhcoqfnjjuwvxfvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwdmt3aGNvcWZuamp1d3Z4ZnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA3NzQsImV4cCI6MjA2NTU0Njc3NH0.csscU6enlmELF9NNZ8l0K2t3hBKhW_Z5tytw0uaU6DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);